name: Publish to Nuget
on:
  push:
    branches: [ master ]
    
jobs:
  publish:
    name: Build, pack and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2        
      - name: Publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ./src/Aurora.EmailParser/Aurora.EmailParser.csproj
          VERSION_REGEX: <Version>(.*)<\/Version>
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
